sudo: required

services:
  - docker

language: java
jdk:
- oraclejdk8

env:
  global:
    DOCKER_EMAIL:
      secure: ns2Xzc+REPXVgvmu69optEv7dZDulYkaa+h1RSObLsXpoBPvaLXL0bhPzXTw8GVyCBv0onGC3k7yhKuVoTFdWqdrtrAPVtPBJRYEr1aP2R6igIIbI/zVpyl3CJhoH3BAQO4Ve1KEOibcC+xtyI22BPQTuYORoZnyWgwM24cLtQwiVnjpGePfH3R4rQydcmwZ4Ucg/4/n9nINnJsOrQmayIn3F5GqHjcP5zAurOB82By/wkLHvx3TUyXR+6LwSgb/00oIk4TUl8q832d+4aVsGR7qiX7eFIZ7jHP/8zFNJpb5yIl+QD6QNiw4Lkg8Qeo+a9LdHrX8EAftSd+xEJuaHe0oFiHcNeDmQu0TkCQQvQZM+d1icum9KpjzL9Lkru7ER/Wuc4tFekofD6lGVfCumTiA5tVCRM2uSFxGz9/lU99SJHgqA9YpAwE9oGaCUrNQUfZNJxXFcimD8/Shi+hDuCfZwfOwn9MF6Y6U87u2M+WlDt5FQT378whYbKRYWOtGH/ZU5uUauxOnVO10Z6TVmB+SPgGFYGUiY8zNMtrehHhYNBnWsC9UddVPJwdTBABefBl7cmb2CErjNcyJgArZyaOKeL0iCfexlc66yO5hBcwd0O1iQmdTHMI6vkev/3nyHe+dUx9B7dCpgWukYW09OmWl71+GKFB4QICby6bEglY=
    DOCKER_USER:
      secure: GezegNgFH7/JkI7uDKep/xyfWNGIDjNfAcf4lfIYQ67jGmWlBOkTPT2atv6T750zLMy9jav6JsrHOQiRsHDMfONcr9+w1J+9eXTAA7vF1Y91csq9xhDJ9Vdfga6I0W32iitzRq4VSHybCzZN+MJ1lEWNBqQo8WkTfvEwnDTVMpBNPuK7xY1soTk7MOoApuaoZ33jhbUAa2IqW2BQ9q5O4fT/jRtPwuNVkwRNo8i48v0MFYmQJeAePwwbumOXVgszLJsGhr1eft2RXgcLtOk5/cxwfx0PoeFkJHodaEOrOzu15LQmmMsGMkgkFVQaWLwvoj0w3DJm1ON7vieXPv2eX1SexSeEsIBh/da9BVKk9OG5pbfs4PhCmOlHzrCWSDmxCQ4/6FtDnz3yU/Sw8wUQfS3+gcG+Qh8bD/AD2dgrvndRy2oFBy0XWGTPQ0SkLR0mYGPXLWbdangQBsBt42leu9tGQoE7JDKBhh7Sioip7/K8WspSBnyksTXOCZeLd9SHmbf+N4jYCAjkLkH3yNkbhuAPXpWb/2ZcMnYAl+K6u/Go+eq9IwC/uL93NUn1eDa4OBd1GGUo5UrpbcCTZzqymQ1FL9c04D1BYVxVIgGo8wdavMcI9mJwC1I7531L+9IWe8XFUGcy7pNHlRlIMhLy9OH1FVrm1DAkVMg9J3BI1x8=
    DOCKER_PASS:
      secure: PTPubzJrgCovsgFnTesEHMQCQOQkdiCjUaXMpeixfkR/RnetRIOLNpmUsrTm4LAdGNZj/HE4TYZysmDOKkPDWAgMQDGwieuIBv/gNiJNtSjy77YuKr5vGAeJVlVWLMB/WbA+GimadEhUBtxUAcEBNE+Bl/2Vf23P+eZLd3rKx4o9tm5QFL2z8OE3a/W2pt4yM/kQj9hOL1XMfhQ33INfWPIRF7tkV/WYZgDNe/oCd+QGL7JgyKXKhikjYoSCl0PbEG4S/erj0l8wcDh4k4jVfZpwCUaZxsO0KlPiimdaKjpzdpda5aunW5wsdzPI3APHNeuNm5jFNPSOGSC7Jr4Mi/5VeXwwhQ289y7P0d+PwUHXL3yDeL2fhbm4np3I68QKRQUHkX8BzRSrpK5B2eg9XrCJ0GLWGxcZib7dQE9sitlhfdPKAXqLPxoBveyIYM36DnTave5lOwaqpQUc1k1oHsqxjpYU0PlqX2xCc6RuW9CynzFdoTj6D4liaj3lN/pATOZfIfHONFCQL+7TY1snPf3OReQ9xkYZWwlV2A+DXoeyyuvuolk2HbqWvAm8rLuBfaRbM0LwL/Cb5Cb7djSrF5kVQpPf5kZhMUjIcoKcl+FQQ/0P51EHhUU7W3q29tUjgCm5Ts48bcCwMYxMo/S2ZjqrBKR9Cze+47/Z+a4IhIk=
    COMMIT: ${TRAVIS_COMMIT::6}

cache:
  directories:
    - "$HOME/.m2"

script:
  - mvn clean install

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=$DOCKER_USER/cloud-shop
  - export TAG=$TRAVIS_BRANCH
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker push $REPO
