sudo: required

services:
- docker

language: java
jdk:
- oraclejdk8

env:
  global:
    DOCKER_USER: "shboland"
    DOCKER_PASS:
      secure: "VZe2uS5VYPLkdy557QUnGN4WsZQZVi5dT0pj1MHiTGg6AdzhT14iT3ZCrTfb/bhrqEjMWKTIWu5aKQdTmnAS1ChDV/VnzHwPS6K0XlIvoth7uoaCLc5L+2+/IGYOBEnaXo+Oj1LLQP/pcfgks4FgxKHVEzByCzYfNox1poOjRTCF6CYvZUlPQHc2TSlLTL4NaPZ0DD3lR1YyJdoWgC/f+mxSYenrGvX2zGdreaPpFsAI+TBn6gOtuM7aB+f/5BePHEa1M8ufgnklG0G93qc5KzUzEtz8v4iuCKCEo+KT8tCiEzFyBQc0MpxnPw+CORcn2YUDcmgkvunI9D8/FXOwarwxg+iL/eCI+oXqpGB3BQG9vTc7EyncC+cKA9gk/cGp4QTt/jP94lGB+C4ztpb19ot/DkMkozs/IIu27BeRLj/DE04N0vMHpNj+f2u7wA81mAUq7UZ2tXwsM3kejLgR273N5fTz4QSiF1usmwhKUosXMsJI4Kvyj29vAmz95V/O+h+49nvXNmmDawv8tvpYeY9oVe2lIc6q2UrOHcDsc26lGUfjoBuNsClxMQSUrZrRc/B16sPOEEslzhkH2HgTDPocNw5ixRT1d5m2uh45dNg/QNhCo/2HHQ6XvromgUr4+rqd9DwiT3MmKScPqSCr1KR3voNuTWzBToW4Zm06qUw="
    COMMIT: ${TRAVIS_COMMIT::6}

cache:
  directories:
  - "$HOME/.m2"

script:
- docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
- mvn clean install -DpushImage
