discovery-service:
  image: shboland/discovery-service:1.0.0
  restart: always
  ports:
   - 8761:8761

inventory-service:
  image: shboland/inventory-service:1.0.0
  restart: always
  environment:
   - SPRING_PROFILES_ACTIVE=development
  links:
    - mysql
    - discovery-service

basket-service:
  image: shboland/basket-service:1.0.0
  restart: always
  environment:
   - SPRING_PROFILES_ACTIVE=development
  links:
    - mysql
    - discovery-service

edge-service:
  image: shboland/edge-service:1.0.0
  restart: always
  ports:
    - 9000:9000
  links:
    - discovery-service

mysql:
  image: mysql:5.7
  ports:
   - 3366:3306
  environment:
   - MYSQL_ROOT_PASSWORD=dbpass
