discovery-service:
  image: sboland/discovery-service
  ports:
   - 8761:8761

inventory-service:
  image: sboland/inventory-service
  links:
    - discovery-service

shopping-cart-service:
  image: sboland/basket-service
  links:
    - discovery-service

edge-service:
  image: sboland/edge-service
  ports:
    - 9000:9000
  links:
    - discovery-service
