neo4j:
  image: neo4j:2.3
  ports:
   - 7474:7474
  environment:
   - NEO4J_AUTH=none
inventory-service:
  image: sboland/inventory-service
  links:
   - neo4j
  environment:
   - SPRING_PROFILES_ACTIVE=docker
   - DOCKER_IP=$DOCKER_IP