discovery-service:
  image: shboland/discovery-service
  restart: always
  ports:
   - 8761:8761

inventory-service:
  image: shboland/inventory-service
  restart: always
  environment:
   - SPRING_PROFILES_ACTIVE=production
  links:
    - discovery-service

basket-service:
  image: shboland/basket-service
  restart: always
  environment:
   - SPRING_PROFILES_ACTIVE=production
  links:
    - discovery-service

edge-service:
  image: shboland/edge-service
  restart: always
  ports:
    - 9000:9000
  links:
    - discovery-service
